# Generated by Django 4.1.5 on 2023-01-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaBookingSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='date_of_birth',
            field=models.CharField(default='2nd September 2000', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='first_name',
            field=models.CharField(default='Adrian', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='last_name',
            field=models.CharField(default='Mitrea', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='password',
            field=models.CharField(default='janedoe1234', max_length=15),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='username',
            field=models.CharField(default='jane02', max_length=20),
        ),
    ]
