# Generated by Django 4.1.5 on 2023-01-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaBookingSystem', '0002_alter_userdetails_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='address',
            field=models.CharField(default='BS7 0JL', max_length=100),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='email',
            field=models.CharField(default='adrianmitrea20@yahoo.com', max_length=100),
        ),
    ]
