# Generated by Django 4.1.5 on 2023-01-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaBookingSystem', '0003_userdetails_address_userdetails_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_name', models.CharField(default='Spiderman: No Way Home', max_length=100)),
                ('film_description', models.CharField(default="With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell \n                                                                        goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.", max_length=300)),
                ('film_duration', models.CharField(default='2h and 28 mins', max_length=30)),
                ('film_age_rating', models.CharField(default='8+', max_length=50)),
                ('film_release_date', models.CharField(default='15th December 2021', max_length=50)),
            ],
        ),
    ]
